version: '2'
services:
    aniviptest-app:
        image: aniviptest
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://aniviptest-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=anivipTest
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    aniviptest-mongodb:
        extends:
            file: mongodb.yml
            service: aniviptest-mongodb
