version: '2'
services:
    aniviptest-mongodb:
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/anivipTest/mongodb/:/data/db/
